packages:
  - packages/*
  - docs

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080
trustPolicy: downgrade
trustedDependencies:
  - semver
blockExoticSubdeps: true
allowBuilds:
  esbuild: true
