packages:
  - packages/*

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustedDependencies:
  - semver
blockExoticSubdeps: true
allowBuilds:
  esbuild: true
